#!/usr/bin/env bash

git clone -b v3.1.1 https://gitlab.com/taciturn-pachyderm/canvas-libs

unameOutput="$(uname -o)"
echo "${unameOutput}"

if [ "${unameOutput}" == "Cygwin" ]; then
    nohup cygstart index.html
elif [ "${unameOutput}" == "GNU/Linux" ]; then
    nohup xdg-open index.html
fi
rm nohup.out

